# RubyTwitterStats config file

mentions:
  enabled: true   # Enable "Most mentioned users" list
  top: 10         # How many users to show on the "Most mentioned users" list
  notop: 20       # How many users to show on the "These didn't make it to the top" list
clients:
  enabled: true   # Enable "Most used clients" list
  top: 10         # How many clients to show on the "Most used clients" list
  notop: 20       # How many clients to show on the "These didn't make it to the top" list
hashtags:
  enabled: true   # Enable "Most used hashtags" list
  top: 10         # How many hashtags to show on the "Most used hashtags" list
  notop: 20       # How many hashtags to show on the "These didn't make it to the top" list

# kate: indent-width 2